version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command:  |
            gem install jekyll
            npm install

      - run: npm run gulp build

      # deploy if green
      - deploy:
          name: Deploy site
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               .circleci/deploy-ghpages.sh
            fi
